application: myeventbot
version: 1
runtime: python
api_version: 1

default_expiration: "4h"

handlers:
- url: /_ah/mail/.+ 
  script: incoming_mail.py
- url: /.*\.html|/
  script: static_html.py
- url: /static
  static_dir:  static
- url: /register
  script: registration.py

inbound_services:
- mail
