application: myeventbot-hrd
version: testing
runtime: python27
threadsafe: true
api_version: 1

default_expiration: "4h"

handlers:
- url: /_ah/mail/.+
  script: incoming_mail.app
- url: /.*\.html|/
  script: static_html.app
- url: /static
  static_dir:  static
- url: /version.txt
  static_files: version.txt
  upload: version.txt
  expiration: 0s
  login: admin
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /register
  script: registration.app
  secure: always
- url: /authorize
  script: registration.app
  login: required
- url: /test.*
  script: lib.gaeunit.app
  login: admin
- url: /admin/.*
  script: admin.app
  login: admin
- url: /update_stats
  script: update_stats.app
  login: admin
- url: /livecount/.*
  script: livecount.counter.application
  login: admin
- url: /migrate_one_user
  script: migrate_users.app
  login: admin

admin_console:
  pages:
  - name: Stats
    url: /admin/dashboard

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.less$

builtins:
- remote_api: on
- deferred: on
- appstats: on

inbound_services:
- mail

libraries:
- name: jinja2
  version: "2.6"
