application: myeventbot
version: testing
runtime: python
api_version: 1

default_expiration: "4h"

handlers:
- url: /_ah/mail/.+ 
  script: incoming_mail.py
- url: /.*\.html|/
  script: static_html.py
- url: /static
  static_dir:  static
- url: /version.txt
  static_files: version.txt
  upload: version.txt
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /register
  script: registration.py
  secure: always
- url: /test.*
  script: lib/gaeunit.py
  login: admin
- url: /dashboard
  script: dashboard.py
  login: admin
- url: /update_stats
  script: update_stats.py
  login: admin

admin_console:
  pages:
  - name: Dashboard
    url: /dashboard

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.less$
  
inbound_services:
- mail
