application: myeventbot-hrd
version: testing
runtime: python27
threadsafe: no
api_version: 1

default_expiration: "4h"

handlers:
- url: /_ah/mail/.+ 
  script: incoming_mail.py
- url: /.*\.html|/
  script: static_html.py
- url: /static
  static_dir:  static
- url: /version.txt
  static_files: version.txt
  upload: version.txt
  expiration: 0s
  login: admin
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /register
  script: registration.py
  secure: always
- url: /authorize
  script: registration.py
  login: required
- url: /test.*
  script: lib/gaeunit.py
  login: admin
- url: /admin/.*
  script: admin.py
  login: admin
- url: /update_stats
  script: update_stats.py
  login: admin

admin_console:
  pages:
  - name: Stats
    url: /admin/dashboard

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.less$

builtins:
- remote_api: on

inbound_services:
- mail
