application: myeventbot
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/.+ 
  script: incoming_mail.py
- url: /static
  static_dir:  static
- url: .*
  script: main.py

inbound_services:
- mail
