application: myeventbot
version: 2
runtime: python
api_version: 1

default_expiration: "4h"

handlers:
- url: /_ah/mail/.+ 
  script: incoming_mail.py
- url: /.*\.html|/
  script: static_html.py
- url: /static
  static_dir:  static
- url: /migrate
  script: migrate.py
  login: admin
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /register
  script: registration.py
  secure: always
- url: /test.*
  script: gaeunit.py
  login: admin

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.less$
  
inbound_services:
- mail
