application: myeventbot
version: 1
runtime: python
api_version: 1

default_expiration: "4h"

handlers:
- url: /_ah/mail/.+ 
  script: incoming_mail.py
- url: /googleea49d973c233620a.html
  static_files: googleea49d973c233620a.html
  upload: googleea49d973c233620a.html
- url: /static
  static_dir:  static
- url: .*
  script: main.py

inbound_services:
- mail
